WITH CUSTOMERORDER AS (
    SELECT C.CUSTOMERID, CONCAT(C.FIRSTNAME, ' ', C.LASTNAME) AS CUSTOMERNAME, COUNT(O.ORDERID) AS ORDERCOUNT
    FROM L1_LANDING.customers C
    JOIN l1_landing.orders O ON C.CUSTOMERID = O.CUSTOMERID
    GROUP BY C.CUSTOMERID, CUSTOMERNAME
    ORDER BY ORDERCOUNT DESC
)

SELECT CUSTOMERID, CUSTOMERNAME, ORDERCOUNT
FROM CUSTOMERORDER